# Site settings
title: Sergey Buyanov CV
#description: Sergey's CV
favicon: /assets/img/avatar.JPG
#baseurl: https://usbuyanov.github.io/resume
#url: https://usbuyanov.github.io/resume
#rss_url: /pages/atom.xml
google_analytics: UA-138708888-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Sergey Buyanov
  title: Sr Devops engineer
  address: New york ,USA 
  email: usbuyanov#gmail.com
  weibo:
  github: usbuyanov
  linkedin: sergeybuyanov
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
  workHistory:
    - work3:
      company: Virtualhealth
      location: New York
      title: Devops engineer
      started: 2020
      duration: (June 2020 - March 2021)
      description: Integrated Terraform modules with Ansible, enhancing deployment speed by 40% and system efficiency. Automated via Jenkins multi-stage pipelines for a SaaS application.
                   Established a secure CI/CD pipeline for deploying Datadog monitor resources using Terraform modules, collaborating closely with developers to reinforce a resilient platform engineering framework. This initiative streamlined monitoring workflows and reduced critical alerts by over 70%, enhancing system reliability and operational efficiency.
                   Guide a migration from monolithic to microservices architecture, improving system scalability and fault isolation while reducing deployment risks. 

    - work2:
      company: Digital Edge Ventures
      location: New York
      title: Devops engineer
      started: 2019
      duration: (February 2019  - June 2020)
      description:   Implemented Infrastructure as Code (IaC) with Terraform and Ansible on AWS, significantly cutting provisioning time in a mixed Windows and Linux environment within the finance sector. 
                     Enhanced CI/CD pipelines with Jenkins and Docker, boosting deployment frequency from weekly to daily. 
                     Crafted data models for serverless architectures, balancing performance with cost-effectiveness in AWS Lambda implementations. 
                     Spearheaded SOC2 compliance initiatives, fortifying the organizational security posture. Fostered cross-functional teamwork, aligning DevOps practices with business objectives to drive technological advancement and operational excellence. 

    - work1:
      company: Sibers
      location: Novosibirsk, Russia
      title: DevOps Engineer
      started: 2007
      duration: (April 2007 - January 2019)
      description:   LAMP stack performance, improving server efficiency and reducing response times through fine-tuned configurations and proactive monitoring. 
                     Spearheaded the deployment of scalable and cost-effective cloud infrastructure on AWS and Azure, showcasing expertise in cloud architecture and implementation. 
                     Automated CI/CD pipelines using Jenkins with Git webhooks and Poll SCM, streamlining workflows and reducing deployment time. 
                     Designed and managed virtualization environments using Proxmox VE, deploying and maintaining highly available clusters for production workloads.
                     Administered source code management systems (GIT and SVN) and issue tracking tools (Redmine), ensuring smooth collaboration across cross-functional teams. 
                     Developed and implemented custom Bash and Python scripts to automate routine tasks, significantly improving team productivity and reducing manual workload.

  educationHistory:
    - education1:
      organization: Novosibirsk University
      location: Novosibirsk, Russia
      degree: Masters
      major: Computer Science
      started: 1989
      duration: (1989 - 1995)
      description:
  languages:
    - language2:
      name: English
      proficiency: Fluent
    
  programmingSkills:
    - skill1:
      name: Amazon AWS
      percentage: 100%
    - skill2:
      name: Microsoft Azure
      percentage: 80%
    - skill3:
      name: Linix
      percentage: 95%
    - skill4:
      name: DevOps tool (GIT, Ansible,Terraform, Docker, Grafana)
      percentage: 90%
    - skill5:
      name: Windows Server (Active Direcrory, IIS)
      percentage: 90%
