# Site settings
title: Sergey Buyanov CV
#description: ddbullfrog's CV
favicon: /assets/img/avatar.JPG
#baseurl: https://ddbullfrog.github.io/resumecard
#url: https://ddbullfrog.github.io/resumecard
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Sergey Buyanov
  title: Devops/System enginner
  address: Brooklyn, New york
  email: usbuyanov#gmail.com
#  link: http://ddbullfrog.com
  weibo:
  github: usbuyanov
  linkedin: sergeybuyanov
#  twitter: ddbullfrog
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Digital Edge
      location: New York
      title: System Engineer
      started: 2019
      duration: (February 2019  - Present)
      description: Migrating on premise datacenter to Amazon AWS infrastructure. Implementing monitoring solutions Prometheus- Grafana to monitor health of systems VMware, AWS Amazon and generate proactive alerts in Slack channel for systems entering a degraded state. Managing infrastructure as code (IaC) via source control GIT and Ansible. Implementing Open Source solutions for best practice managing infrastructure
    - work2:
      company: Sibers
      link: sibers.com
      location: Novosibirsk, Russia
      title: DevOps Engineer
      started: 2007
      duration: (2007 - 2018)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2009
      duration: (2009 - 2012)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: XXXXXX University
      location: Shenyang, China
      degree: Bachelor
      major: Software Engineering
      started: 2005
      duration: (2005 - 2009)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Russian
      proficiency: Native
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 100%
    - skill2:
      name: Bootstrap
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 70%
    - skill4:
      name: AngularJS
      percentage: 70%
    - skill5:
      name: Java/Java EE
      percentage: 90%
