# Site settings
title: Sergey Buyanov Resume
#description: Sergey's CV
favicon: /assets/img/avatar.JPG
#baseurl: https://usbuyanov.github.io/resume
#url: https://usbuyanov.github.io/resume
#rss_url: /pages/atom.xml
google_analytics: UA-138708888-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Sergey Buyanov
  title: Sr Devops engineer
  address: New york ,USA 
  email: usbuyanov#gmail.com
  weibo:
  github: usbuyanov
  linkedin: sergeybuyanov
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
  workHistory:
    - work6:
      company: Fast Retailing
      location: New York, Hybryd
      title: Sr Devops engineer
      started: 2025
      duration: (January 2024- Pesent) 
      description:
  
    - work5:
      company: FULLBEAUTY Brands
      location: New York, Hybryd
      title: Sr Devops engineer
      started: 2024
      duration: (January 2024- February 2025)
      description: Collaboratively migrated and architected a legacy application to a serverless architecture using GitOps with AWS CodePipeline, Lambda, AWS ECS, API Gateway, RDS Aurora Serverless, Apache Airflow, and DynamoDB, reducing FinOps costs by 37% while enhancing scalability and operational efficiency. Partnered with ML teams to streamline data workflows and support model deployment pipelines.
                   Developed automated solutions for replicating production and staging RDS PostgreSQL databases, reducing data sync time by 60% and ensuring high availability and consistency across environments.
                   Automated security compliance checks using Terraform, Prowler, AWS ECS, Lambda, Cloud watch and Security HUB reducing manual audit efforts by 60% and improving cloud security posture through proactive communication with security team.
                   Migrated from manual resource management to Infrastructure as Code (IaC) using Terraform, AWS CDK, and SAML, cutting deployment time by 70% and improving cross-team efficiency and consistency.
                   Demonstrated exceptional problem-solving ability in resolving critical system issues in the capacity of a Senior DevOps Engineer
                   Transited CI/CD deployment pipelines from CircleCI to AWS Code Pipeline
  
    - work4:
      company: Aligntech
      location: New York, Remote
      title: Sr Devops engineer
      started: 2021
      duration: (March 2021- November 2023)
      description:   Led the migration from Rancher to AWS EKS Kubernetes, leveraging Terraform, Helm, Argo CD, FluxCD and JFrog Artifactory, reducing deployment time by 60%. Integrated Splunk and SignalFX, improving system monitoring and cutting incident response time by 40%.
                     Designed, application development and deployed scalable serverless applications on AWS using Python (Django), REST APIs, API Gateway, Step Functions, Kubernetes and Lambda, reducing operational costs by 50% while improving system performance.
                     Experienced in using Ansible for automating infrastructure management and deployment. Proficient in writing Ruby-based Chef recipes and cookbooks to manage system configurations, package installations, and service management in both Windows and Linux (Ubuntu) environments.
                     Developed a zero-trust security model for cloud environments, incorporating network segmentation, identity-based access controls, and automated compliance checks
  
    - work3:
      company: Virtualhealth
      location: New York, Remote
      title: Devops engineer
      started: 2020
      duration: (June 2020 - March 2021)
      description: Integrated Terraform modules with Ansible, enhancing deployment speed by 40% and system efficiency. Automated via Jenkins multi-stage pipelines for a SaaS application.
                   Established a secure CI/CD pipeline for deploying Datadog monitor resources using Terraform modules, collaborating closely with developers to reinforce a resilient platform engineering framework. This initiative streamlined monitoring workflows and reduced critical alerts by over 70%, enhancing system reliability and operational efficiency.
                   Guide a migration from monolithic to microservices architecture, improving system scalability and fault isolation while reducing deployment risks. 

    - work2:
      company: Digital Edge Ventures
      location: New York, Onsite
      title: Devops engineer
      started: 2019
      duration: (February 2019  - June 2020)
      description:   Implemented Infrastructure as Code (IaC) with Terraform and Ansible on AWS, significantly cutting provisioning time in a mixed Windows and Linux environment within the finance sector. 
                     Enhanced CI/CD pipelines with Jenkins and Docker, boosting deployment frequency from weekly to daily. 
                     Crafted data models for serverless architectures, balancing performance with cost-effectiveness in AWS Lambda implementations. 
                     Spearheaded SOC2 compliance initiatives, fortifying the organizational security posture. Fostered cross-functional teamwork, aligning DevOps practices with business objectives to drive technological advancement and operational excellence. 

    - work1:
      company: Sibers
      location: Novosibirsk, Russia
      title: DevOps Engineer
      started: 2007
      duration: (April 2007 - January 2019)
      description:   LAMP stack performance, improving server efficiency and reducing response times through fine-tuned configurations and proactive monitoring. 
                     Spearheaded the deployment of scalable and cost-effective cloud infrastructure on AWS and Azure, showcasing expertise in cloud architecture and implementation. 
                     Automated CI/CD pipelines using Jenkins with Git webhooks and Poll SCM, streamlining workflows and reducing deployment time. 
                     Designed and managed virtualization environments using Proxmox VE, deploying and maintaining highly available clusters for production workloads.
                     Administered source code management systems (GIT and SVN) and issue tracking tools (Redmine), ensuring smooth collaboration across cross-functional teams. 
                     Developed and implemented custom Bash and Python scripts to automate routine tasks, significantly improving team productivity and reducing manual workload.

  educationHistory:
    - education1:
      organization: Novosibirsk State University
      #location: Novosibirsk, Russia
      degree: Bachelors
      major: Computer Science
      #started: 1989
      #duration: (1989 - 1995)
      description:
  languages:
    - language2:
      name: English
      proficiency: Fluent
    
  programmingSkills:
    - skill1:
      name: Cloud AWS|Azure|GCP
      percentage: 100%
    - skill2:
      name: Containers Docker|Kubernetes|Fargate|Helm|Microservices
      percentage: 100%
    - skill3:
      name: Systems Linux|Windows
      percentage: 100%
    - skill4:
      name: CI/CM ArgoCD|Ansible|Jenkins|Terraform|CodePipeline|CircleCi
      percentage: 100%
    - skill5:
      name: Database MySQL|MSSQL|DynamoDB|Postgress|MongoDB
      percentage: 90%
