# Site settings
title: Sergey Buyanov CV
#description: Sergey's CV
favicon: /assets/img/avatar.JPG
#baseurl: https://usbuyanov.github.io/resume
#url: https://usbuyanov.github.io/resume
#rss_url: /pages/atom.xml
google_analytics: UA-138708888-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Sergey Buyanov
  title: Devops engineer
  address: New york ,USA 
  email: usbuyanov#gmail.com
  weibo:
  github: usbuyanov
  linkedin: sergeybuyanov
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
  workHistory:
    - work1:
      company: Digital Edge Ventures
      location: New York
      title: Devops/System engineer
      started: 2019
      duration: (February 2019  - June 2020)
      description:  •	Experience in working on AWS and its services like AWS IAM, VPC, EC2, ECS, EBS, RDS, S3, Lambda, ELB, Auto Scaling, Route 53, Cloud Front, Cloud Watch, Cloud Trail, Fargate, EKS.
                      Designed and implemented a complex IaC Infrastructure from scratch on AWS: multi-tier, multi-subnet scalable cloud AWS infrastructure, Docker, platform-agnostic local environments with Docker and docker-compose.
                   •	Designing and implementing build, deployment, and configuration management
•	Building and testing automation tools for infrastructure provisioning on permice and AWS (Ansible, Terraform, Cloud formation)
•	Monitoring metrics and develop ways to improve (Prometheus, Grafana, Inflixdb, telegraf)
•	Managing CI and CD tools with a team (Teamcity, Jenkins)
•	Wrote several Ansible playbooks for the automation that was defined through tasks using YAML format and run Ansible Scripts to provision Dev servers
•	Designed the data models to be used in AWS Lambda applications (Python) which are aimed to do complex reduced cost in AWS infrastructure.

    - work2:
      company: Sibers
      location: Novosibirsk, Russia
      title: DevOps Engineer
      started: 2007
      duration: (2007 - 2018)
      description: Designed, implemented, and supported Cloud, and Hybrid Cloud systems, including Office 365, Azure AD, Windows AD, G Suite, Amazon AWS, among others.Responsible for MySQL, MS SQL Server and PostgreSQL installations, monitoring, and support. Administered Red Hat Linux/CentOS systems.Maintained and administered Team Foundation Server (TFS) Performed system monitoring, upgrades, performance tuning, and backup and recovery.Installed and configured tuning Apache (Apache Tomcat), Nginx in a LAMP stack. Developed Amazon AWS Cloud Formation templates to create custom sized VPC, subnets, EC2 instances, ELB, Security Groups, load balancer. Deployed and monitored scalable infrastructure on Amazon Web Services (AWS) & configuration management using Ansible. Used AWS Beanstalk for deploying and scaling web applications and services developed with Java, PHP, Node.js, Python, Ruby, and Docker on familiar servers such as Apache, and IIS. Worked on Docker Hub, creating Docker images and handling multiple images primarily for middleware installations and domain configuration. Deployed and configured OpenStack components.Supported QA and Dev to develop standard platforms meeting requirements of consistent production.Maintained and administered GIT, SVN, Redmine -source code management tool and issue tracker. Used Nagios, Splunk tool for Monitoring. Automated routine work through Bash /Python scripts. Used Kubernetes (Amazon EKS) to deploy scale, load balance, and manage Docker containers with multiple namespace versions.

  educationHistory:
    - education1:
      organization: Novosibirsk University
      location: Novosibirsk, Russia
      degree: Masters
      major: Computer Science
      started: 1989
      duration: (1989 - 1995)
      description:
  languages:
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Russian
      proficiency: Native
  programmingSkills:
    - skill1:
      name: Amazon AWS
      percentage: 100%
    - skill2:
      name: Microsoft Azure
      percentage: 80%
    - skill3:
      name: Linix
      percentage: 95%
    - skill4:
      name: DevOps tool (GIT, Ansible,Terraform, Docker, Grafana)
      percentage: 90%
    - skill5:
      name: Windows Server (Active Direcrory, IIS)
      percentage: 90%
