# Site settings
title: Sergey Buyanov CV
#description: ddbullfrog's CV
favicon: /assets/img/avatar.JPG
#baseurl: https://ddbullfrog.github.io/resumecard
#url: https://ddbullfrog.github.io/resumecard
rss_url: /pages/atom.xml
google_analytics: UA-138708888-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Sergey Buyanov
  title: Devops/System enginner
  address: Brooklyn, New york
  email: usbuyanov#gmail.com
#  link: http://ddbullfrog.com
  weibo:
  github: usbuyanov
  linkedin: sergeybuyanov
#  twitter: ddbullfrog
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Digital Edge Ventures
      location: New York
      title: System Engineer
      started: 2019
      duration: (February 2019  - Present)
      description: Migrating on premise datacenter to Amazon AWS infrastructure. Implementing monitoring solutions Prometheus- Grafana to monitor health of systems VMware, AWS Amazon and generate proactive alerts in Slack channel for systems entering a degraded state. Managing infrastructure as code (IaC) via source control GIT and Ansible. Implementing Open Source solutions for best practice managing infrastructure
    - work2:
      company: Sibers
      location: Novosibirsk, Russia
      title: DevOps Engineer
      started: 2007
      duration: (2007 - 2018)
      description: Designed, implemented, and supported Cloud, and Hybrid Cloud systems, including Office 365, Azure AD, Windows AD, G Suite, Amazon AWS, among others.Responsible for MySQL, MS SQL Server and PostgreSQL installations, monitoring, and support. Administered Red Hat Linux/CentOS systems.Maintained and administered Team Foundation Server (TFS) Performed system monitoring, upgrades, performance tuning, and backup and recovery.Installed and configured tuning Apache (Apache Tomcat), Nginx in a LAMP stack. Developed Amazon AWS Cloud Formation templates to create custom sized VPC, subnets, EC2 instances, ELB, Security Groups, load balancer. Deployed and monitored scalable infrastructure on Amazon Web Services (AWS) & configuration management using Ansible. Used AWS Beanstalk for deploying and scaling web applications and services developed with Java, PHP, Node.js, Python, Ruby, and Docker on familiar servers such as Apache, and IIS. Worked on Docker Hub, creating Docker images and handling multiple images primarily for middleware installations and domain configuration. Deployed and configured OpenStack components.Supported QA and Dev to develop standard platforms meeting requirements of consistent production.Maintained and administered GIT, SVN, Redmine -source code management tool and issue tracker. Used Nagios, Splunk tool for Monitoring. Automated routine work through Bash /Python scripts. Used Kubernetes (Amazon EKS) to deploy scale, load balance, and manage Docker containers with multiple namespace versions.
    - work3:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2009
      duration: (2009 - 2012)
  educationHistory:
    - education1:
      organization: Novosibirsk University
      location: Novosibirsk, Russia
      degree: Masters
      major: Computer Science
      started: 1989
      duration: (1989 - 1995)
      description:
  languages:
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Russian
      proficiency: Native
  programmingSkills:
    - skill1:
      name: Amazon AWS
      percentage: 100%
    - skill2:
      name: Microsoft Azure
      percentage: 80%
    - skill3:
      name: Linix
      percentage: 95%
    - skill4:
      name: DevOps tool (GIT, Ansible, Docker, Grafana)
      percentage: 90%
    - skill5:
      name: Windows Server (Active Direcrory, IIS)
      percentage: 90%
