# Site settings
title: Sergey Buyanov CV
#description: Sergey's CV
favicon: /assets/img/avatar.JPG
#baseurl: https://usbuyanov.github.io/resume
#url: https://usbuyanov.github.io/resume
#rss_url: /pages/atom.xml
google_analytics: UA-138708888-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Sergey Buyanov
  title: Sr Devops engineer
  address: New york ,USA 
  email: usbuyanov#gmail.com
  weibo:
  github: usbuyanov
  linkedin: sergeybuyanov
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
  workHistory:
    - work1:
      company: Digital Edge Ventures
      location: New York
      title: Devops/System engineer
      started: 2019
      duration: (February 2019  - June 2020)
      description:   Implemented Infrastructure as Code (IaC) with Terraform and Ansible on AWS, significantly cutting provisioning time in a mixed Windows and Linux environment within the finance sector. 
                     Enhanced CI/CD pipelines with Jenkins and Docker, boosting deployment frequency from weekly to daily. 
                     Crafted data models for serverless architectures, balancing performance with cost-effectiveness in AWS Lambda implementations. 
                     Spearheaded SOC2 compliance initiatives, fortifying the organizational security posture. Fostered cross-functional teamwork, aligning DevOps practices with business objectives to drive technological advancement and operational excellence. 

    - work2:
      company: Sibers
      location: Novosibirsk, Russia
      title: DevOps Engineer
      started: 2007
      duration: (2007 - 2018)
      description: Designed, implemented, and supported Cloud, and Hybrid Cloud systems, including Office 365, Azure AD, Windows AD, G Suite, Amazon AWS, among others.Responsible for MySQL, MS SQL Server and PostgreSQL installations, monitoring, and support. Administered Red Hat Linux/CentOS systems.Maintained and administered Team Foundation Server (TFS) Performed system monitoring, upgrades, performance tuning, and backup and recovery.Installed and configured tuning Apache (Apache Tomcat), Nginx in a LAMP stack. Developed Amazon AWS Cloud Formation templates to create custom sized VPC, subnets, EC2 instances, ELB, Security Groups, load balancer. Deployed and monitored scalable infrastructure on Amazon Web Services (AWS) & configuration management using Ansible. Used AWS Beanstalk for deploying and scaling web applications and services developed with Java, PHP, Node.js, Python, Ruby, and Docker on familiar servers such as Apache, and IIS. Worked on Docker Hub, creating Docker images and handling multiple images primarily for middleware installations and domain configuration. Deployed and configured OpenStack components.Supported QA and Dev to develop standard platforms meeting requirements of consistent production.Maintained and administered GIT, SVN, Redmine -source code management tool and issue tracker. Used Nagios, Splunk tool for Monitoring. Automated routine work through Bash /Python scripts. Used Kubernetes (Amazon EKS) to deploy scale, load balance, and manage Docker containers with multiple namespace versions.

  educationHistory:
    - education1:
      organization: Novosibirsk University
      location: Novosibirsk, Russia
      degree: Masters
      major: Computer Science
      started: 1989
      duration: (1989 - 1995)
      description:
  languages:
    - language2:
      name: English
      proficiency: Fluent
    
  programmingSkills:
    - skill1:
      name: Amazon AWS
      percentage: 100%
    - skill2:
      name: Microsoft Azure
      percentage: 80%
    - skill3:
      name: Linix
      percentage: 95%
    - skill4:
      name: DevOps tool (GIT, Ansible,Terraform, Docker, Grafana)
      percentage: 90%
    - skill5:
      name: Windows Server (Active Direcrory, IIS)
      percentage: 90%
